version: '3.2'

services:
  mysql:
    image: mysql:8.0
    networks:
      - task-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task
      MYSQL_USER: task
      MYSQL_PASSWORD: task
  task:
    depends_on:
      - mysql
    image: task-image:0.0.1
    ports:
      - "9093:9093"
    restart: always
    networks:
      - task-network
    volumes:
      - type: bind
        source: C:\logs\task
        target: /logs
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
networks:
  task-network: